
from pydantic import BaseModel, Field
from typing import Literal, List

from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, ToolMessage, AIMessage


class RouterAgentFormat(BaseModel):
    route: Literal["answer_query", "create_ticket"] = Field(description="Decides whether query should be answered via policy documents, ticket creation, or clarification.")
    reason: str = Field(description="Short explanation for why this route was selected.")

class RouterAgent():

    def get_response_format(self):
        return RouterAgentFormat

    def get_prompt_format(self, relevant_items=None):

        user_query = relevant_items["user_query"]
        policy_index = relevant_items["policy_index"]

        system_prompt = f"""

        You are an intelligent IT support routing agent.

        Your job is to analyze a user's query and decide one of the following actions:

        1. answer_query
        - Choose this when the user's question can be answered using existing policy documents.
        - These are usually informational questions such as:
            - How do I reset my password?
            - What is VPN policy?
            - Can I install software?

        2. create_ticket
        - Choose this when the user is reporting an active issue/problem that requires IT intervention.
        - Examples:
            - My laptop is overheating
            - Outlook keeps crashing
            - VPN is not working


        Here is list of available policy documents.
        {policy_index}

        If the query can be answered using one of those documents:
        - select answer_query
        - identify the most relevant document

        If the user is facing a real-time operational issue:
        - select create_ticket

        Be precise and avoid unnecessary ticket creation.
        """

        user_prompt = f"""User Complaint = {user_query}"""

        return [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)], self.get_response_format()
    
class TicketAgent():

    def get_response_format(self):
        return None

    def get_prompt_format(self, relevant_items=None):

        user_query = relevant_items["user_query"]

        system_prompt = f"""

        You are an IT support ticket routing agent.

        Your responsibility is to analyze the user's request and determine whether one of the available tools should be called.

        Rules:
        - Select exactly one appropriate tool.
        - Extract accurate arguments from the user's request.
        - Do not answer the user's request directly.
        - Do not explain your reasoning.
        - Do not call multiple tools.
        - If the request is unclear, choose the tool that best matches the user's intent based on available information.
        - Use only the tools provided to you.
        """

        user_prompt = f"""
        Analyze the following IT support request and determine the appropriate action.

        User Request:
        {user_query}
        """

        return [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)], self.get_response_format()
    
class FinalResponseAgentFormat(BaseModel):
    response_message: str = Field(description="Final user-facing response generated by the assistant.")

class FinalResponseAgent():

    def get_response_format(self):
        return FinalResponseAgentFormat

    def get_prompt_format(self, relevant_items=None):

        user_query = relevant_items["user_query"]

        system_prompt = f"""

        You are an enterprise IT support assistant responsible for generating the final response to the user.

        You will receive:
        - The original user query
        - Previous agent decisions
        - Retrieved knowledge base information (if available)
        - Tool execution results (if available)

        Your job:
        - Generate a clear and professional final response for the user
        - If a knowledge answer was provided, summarize the answer clearly
        - If a ticket/request was created, clearly mention:
            - request/ticket ID
            - assigned team
            - request status
            - request summary
            - Do not mention internal routing logic
            - Do not mention tool names
            - Do not expose raw JSON
            - Try to include all details from tool results
        - Keep the response concise but helpful
        - Try to maintain bullet points, labels and headers
        """

        user_prompt = f"""Users's Original query = {user_query}"""

        return [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)], self.get_response_format()