from FlagEmbedding import FlagModel


model = FlagModel('BAAI/bge-small-en-v1.5', use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation

sentences = [
    "The sun rises in the east every morning.",
    "I enjoy drinking coffee before work.",
    "She bought a new laptop yesterday.",
    "The train arrived ten minutes late.",
    "We went hiking in the mountains last weekend.",
    "My favorite fruit is mango.",
    "The meeting starts at nine o’clock.",
    "He forgot his umbrella at home.",
    "The cat is sleeping on the sofa.",
    "They ordered pizza for dinner.",
    "Artificial intelligence is transforming many industries.",
    "The weather is unusually hot today.",
    "She reads books before going to bed.",
    "The baby laughed at the funny sound.",
    "I need to finish my assignment tonight.",
    "The restaurant serves delicious vegetarian food.",
    "He plays football every Sunday.",
    "My phone battery drains quickly.",
    "We watched a movie last night.",
    "The teacher explained the lesson clearly.",
    "She is learning how to play the guitar.",
    "The dog barked at the stranger.",
    "I forgot to reply to your email.",
    "The garden looks beautiful in spring.",
    "He drives carefully during heavy rain.",
    "They are planning a trip to Japan.",
    "The internet connection is very slow today.",
    "My sister works at a hospital.",
    "The child drew a colorful picture.",
    "We need more chairs for the event.",
    "He enjoys listening to classical music.",
    "The package arrived earlier than expected.",
    "She cleaned her room in the morning.",
    "The birds are singing outside my window.",
    "I lost my wallet at the mall.",
    "The project deadline is next Friday.",
    "He cooked pasta for lunch.",
    "The students prepared for the exam.",
    "We adopted a puppy last month.",
    "She wears glasses while reading.",
    "The flight was delayed due to bad weather.",
    "I like walking in the park.",
    "He forgot his password again.",
    "The company announced new policies.",
    "She baked a chocolate cake.",
    "The car needs fuel.",
    "We visited our grandparents yesterday.",
    "He enjoys solving puzzles.",
    "The phone rang during dinner.",
    "She wrote a letter to her friend.",
    "The library closes at 8 PM.",
    "I need to buy groceries.",
    "The flowers smell wonderful.",
    "He studies mathematics at college.",
    "We played board games all evening.",
    "She painted the walls blue.",
    "The bus stop is nearby.",
    "I enjoy swimming in summer.",
    "He fixed the broken chair.",
    "The doctor prescribed medicine.",
    "We celebrated her birthday.",
    "She loves watching documentaries.",
    "The laptop overheats sometimes.",
    "I missed the morning train.",
    "He works remotely from home.",
    "The museum opens on weekends.",
    "We planted trees in the backyard.",
    "She practiced yoga every day.",
    "The store offers discounts today.",
    "I forgot my notebook at school.",
    "He learned French in college.",
    "The baby is sleeping peacefully.",
    "We need to renew our passports.",
    "She adopted a healthy lifestyle.",
    "The roads were empty at dawn.",
    "I enjoy writing short stories.",
    "He repaired his bicycle.",
    "The concert tickets sold out quickly.",
    "We ordered tea and snacks.",
    "She completed the marathon.",
    "The server crashed unexpectedly.",
    "I need to update my resume.",
    "He enjoys photography.",
    "The classroom was very quiet.",
    "We watched fireworks at night.",
    "She found a lost kitten.",
    "The airport was crowded.",
    "I enjoy gardening on weekends.",
    "He received a promotion.",
    "The cake tastes delicious.",
    "We attended a wedding ceremony.",
    "She studies computer science.",
    "The printer ran out of paper.",
    "I forgot my keys inside the car.",
    "He plays chess online.",
    "The rain stopped suddenly.",
    "We explored the old fort.",
    "She started a new job.",
    "The classroom projector stopped working.",
    "I enjoy learning new languages.",
    "He donated clothes to charity."
]

embeddings_1 = model.encode(sentences)

print(embeddings_1.shape)